version: '2.2'
services:
    mongo:
        restart: always
        image: mongo:latest
        expose:
            - 27017
        volumes:
            - mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    phones:
        restart: always
        image: casperir/phones-backend
        depends_on:
            mongo:
                condition: service_healthy
        expose:
            - 3000
        environment:
            MONGODB_URI: mongodb://mongo/phones
            PORT: 3000

    phones-front:
        restart: always
        image: casperir/phones-frontend
        ports:
            - 80:80
        depends_on:
            - phones

volumes:
    mongo_data: